%% ============================================================
%  B000_Check_Bathy_3DEP_Unit_Ratio.m
%
%  Purpose:
%    Check possible vertical unit mismatch between bathy and 3DEP.
%
%  Input:
%    Processed_Results/Bathy_1m_FixND/<river>/Bathy_1m.vrt
%    Processed_Results/3DEP_1m_VRT/<river>/DEM_3DEP_1m_FixND.vrt
%
%  Output:
%    Z003_Check_Bathy_3DEP_Unit/Check_Bathy_3DEP_Unit.csv
%
%  Notes:
%    - This script does NOT modify data.
%    - It uses gdalinfo -approx_stats, so it is faster than full stats.
%    - The diagnosis is heuristic. A ratio near 3.28 is a strong warning,
%      but final decision should still be checked with metadata and maps.
% ============================================================

clear; clc;
addpath('/tank/data/SFS/xinyis/data/bathymetry/Processed_Results/Z999_Local_Helper')
rootPR = '/tank/data/SFS/xinyis/data/bathymetry/Processed_Results';

bathyRoot = fullfile(rootPR, 'Bathy_1m_FixND');
demRoot   = fullfile(rootPR, '3DEP_1m_VRT');

outRoot = fullfile(rootPR, 'Z003_Check_Bathy_3DEP_Unit');
if exist(outRoot, 'dir') ~= 7
    mkdir(outRoot);
end

outCSV = fullfile(outRoot, 'Check_Bathy_3DEP_Unit.csv');

% Milwaukee children use one common 3DEP folder
milwaukee_children = { ...
    'BadgerFinNull', ...
    'Estabrook_Combined', ...
    'KewaFix2Null', ...
    'Kletzch_Combined_UpMax3Null'};

d = dir(bathyRoot);
d = d([d.isdir]);
d(1:2) = [];

rowsOut = {};

header = { ...
    'River', ...
    'BathyFile', ...
    'DemFile', ...
    'HasBathy', ...
    'HasDEM', ...
    'BathyXSize', ...
    'BathyYSize', ...
    'BathyPixX', ...
    'BathyPixY', ...
    'BathyHorizUnit', ...
    'BathyNoData', ...
    'BathyMin', ...
    'BathyMax', ...
    'BathyMean', ...
    'BathyStd', ...
    'DEMXSize', ...
    'DEMYSize', ...
    'DEMPixX', ...
    'DEMPixY', ...
    'DEMHorizUnit', ...
    'DEMNoData', ...
    'DEMMin', ...
    'DEMMax', ...
    'DEMMean', ...
    'DEMStd', ...
    'MeanRatio_BathyOverDEM', ...
    'MedianRangeRatio_BathyOverDEM', ...
    'PossibleFeetVerticalIssue', ...
    'Notes'};

rowsOut(1, :) = header;

fprintf('Checking %d bathy folders...\n', numel(d));

for i = 1:numel(d)

    river = d(i).name;

    bathyFile = fullfile(bathyRoot, river, 'Bathy_1m.vrt');

    if any(strcmp(river, milwaukee_children))
        demName = 'milwaukee_river_3DEP';
    else
        demName = river;
    end

    demFile = fullfile(demRoot, demName, 'DEM_3DEP_1m_FixND.vrt');

    hasBathy = exist(bathyFile, 'file') == 2;
    hasDEM   = exist(demFile, 'file') == 2;

    fprintf('\n[%d/%d] %s\n', i, numel(d), river);

    notes = '';

    if ~hasBathy
        warning('Missing bathy: %s', bathyFile);
        notes = [notes, 'Missing bathy; '];
    end

    if ~hasDEM
        warning('Missing DEM: %s', demFile);
        notes = [notes, 'Missing DEM; '];
    end

    if hasBathy
        B = getGdalInfoSummary(bathyFile);
    else
        B = emptyInfo();
    end

    if hasDEM
        D = getGdalInfoSummary(demFile);
    else
        D = emptyInfo();
    end

    meanRatio = NaN;
    rangeRatio = NaN;
    possibleFeet = false;

    if hasBathy && hasDEM && isfinite(B.mean) && isfinite(D.mean) && D.mean ~= 0
        meanRatio = B.mean / D.mean;
    end

    % Use mid-range ratio as a second rough indicator.
    % This is less sensitive than min/max alone.
    if hasBathy && hasDEM && ...
       isfinite(B.minv) && isfinite(B.maxv) && ...
       isfinite(D.minv) && isfinite(D.maxv)

        bMid = (B.minv + B.maxv) / 2;
        dMid = (D.minv + D.maxv) / 2;

        if dMid ~= 0
            rangeRatio = bMid / dMid;
        end
    end

    % Heuristic:
    % If bathy/DEM mean ratio is close to 3.28, bathy may still be feet.
    % Use a loose tolerance because bathy and DEM are not exactly identical surfaces.
    if isfinite(meanRatio)
        if meanRatio > 2.6 && meanRatio < 4.0
            possibleFeet = true;
            notes = [notes, 'Mean ratio close to feet/meter factor; '];
        end
    end

    % Additional metadata warning
    if contains(lower(B.horizUnit), 'foot')
        notes = [notes, 'Bathy horizontal CRS unit is foot; gdalwarp -tr must use feet; '];
    end

    if contains(lower(D.horizUnit), 'foot')
        notes = [notes, '3DEP horizontal CRS unit is foot; gdalwarp -tr must use feet; '];
    end

    rowsOut(end+1, :) = { ...
        river, ...
        bathyFile, ...
        demFile, ...
        hasBathy, ...
        hasDEM, ...
        B.xsize, ...
        B.ysize, ...
        B.pixx, ...
        B.pixy, ...
        B.horizUnit, ...
        B.nodata, ...
        B.minv, ...
        B.maxv, ...
        B.mean, ...
        B.stdv, ...
        D.xsize, ...
        D.ysize, ...
        D.pixx, ...
        D.pixy, ...
        D.horizUnit, ...
        D.nodata, ...
        D.minv, ...
        D.maxv, ...
        D.mean, ...
        D.stdv, ...
        meanRatio, ...
        rangeRatio, ...
        possibleFeet, ...
        notes};

    fprintf('  Bathy mean = %.3f, DEM mean = %.3f, ratio = %.3f, possibleFeet = %d\n', ...
        B.mean, D.mean, meanRatio, possibleFeet);
end

writecell(rowsOut, outCSV);

fprintf('\n============================================================\n');
fprintf('Unit diagnostic table written to:\n%s\n', outCSV);
fprintf('============================================================\n');

