#!/usr/bin/env python3
# NUMBER-ALIGNED NAME: A010g_prepare_grouped_holdout_from_existing_LOORO.py
# ORIGINAL BACKUP NAME: A011_prepare_grouped_holdout_from_existing_LOORO.py
# Compatibility rule: scientific logic and default data/result roots are preserved unless explicitly noted.
"""Prepare grouped holdout folds from existing LOORO split/audit files.

This script does NOT re-read GeoTIFFs. It reuses the split lists and audit CSVs
already generated by B010/A010.

Example:
  python A010g_prepare_grouped_holdout_from_existing_LOORO.py \
    --group-name MilwaukeeRiverGroup \
    --member Kletzch_Combined_UpMax3Null \
    --member KewaFix2Null \
    --member BadgerFinNull \
    --member Estabrook_Combined \
    --overwrite
"""
from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

TILE_RE = re.compile(r"^Select_tile_Basin_1m_(.+)_ID\d+\.tif$")


def safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", text)


def read_lines(path: Path) -> List[str]:
    with path.open() as f:
        return [line.strip() for line in f if line.strip()]


def write_lines(path: Path, values: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for value in values:
            f.write(f"{value}\n")


def river_from_dem(path_text: str) -> str:
    name = Path(path_text).name
    match = TILE_RE.match(name)
    if not match:
        raise ValueError(f"Cannot parse river from DEM filename: {name}")
    return match.group(1)


def load_pairs(split_dir: Path) -> List[Tuple[str, str]]:
    dem_train = read_lines(split_dir / "train.txt")
    dem_val = read_lines(split_dir / "val.txt")
    mask_train = read_lines(split_dir / "train_masks.txt")
    mask_val = read_lines(split_dir / "val_masks.txt")
    if len(dem_train) != len(mask_train):
        raise ValueError(f"train DEM/mask length mismatch: {split_dir}")
    if len(dem_val) != len(mask_val):
        raise ValueError(f"val DEM/mask length mismatch: {split_dir}")
    pairs = list(zip(dem_train + dem_val, mask_train + mask_val))
    if len({p[0] for p in pairs}) != len(pairs):
        raise ValueError(f"Duplicate DEM path in source fold union: {split_dir}")
    return pairs


def load_audit_rows(paths: Sequence[Path]) -> Tuple[List[str], Dict[str, dict]]:
    fieldnames: List[str] | None = None
    index: Dict[str, dict] = {}
    basename_index: Dict[str, dict] = {}

    for path in paths:
        with path.open(newline="") as f:
            reader = csv.DictReader(f)
            if reader.fieldnames is None:
                raise ValueError(f"Audit has no header: {path}")
            if fieldnames is None:
                fieldnames = list(reader.fieldnames)
            elif list(reader.fieldnames) != fieldnames:
                raise ValueError(f"Audit headers differ: {path}")

            for row in reader:
                dem_path = (row.get("dem_path") or "").strip()
                if not dem_path:
                    raise ValueError(f"Missing dem_path in {path}")
                if dem_path in index:
                    raise ValueError(f"Duplicate audit dem_path: {dem_path}")
                index[dem_path] = row

                basename = Path(dem_path).name
                if basename in basename_index:
                    raise ValueError(f"Duplicate audit DEM basename: {basename}")
                basename_index[basename] = row

    if fieldnames is None:
        raise ValueError("No audit rows loaded.")
    for basename, row in basename_index.items():
        index[f"__BASENAME__/{basename}"] = row
    return fieldnames, index


def find_audit_row(index: Dict[str, dict], dem_path: str) -> dict:
    row = index.get(dem_path)
    if row is None:
        row = index.get(f"__BASENAME__/{Path(dem_path).name}")
    if row is None:
        raise KeyError(f"No audit row found for DEM path: {dem_path}")
    return row


def write_audit(path: Path, fieldnames: Sequence[str], rows: Sequence[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def status_counts(rows: Sequence[dict]) -> dict:
    counts = Counter((row.get("status") or "UNKNOWN").strip() for row in rows)
    return dict(sorted(counts.items()))


def auto_source_fold(cv_root: Path) -> str:
    candidates = sorted((cv_root / "splits").glob("holdout_*"))
    for split_dir in candidates:
        required = [
            split_dir / "train.txt",
            split_dir / "val.txt",
            split_dir / "train_masks.txt",
            split_dir / "val_masks.txt",
        ]
        if all(path.is_file() for path in required):
            return split_dir.name.replace("holdout_", "", 1)
    raise FileNotFoundError(f"No complete holdout_* split found under {cv_root / 'splits'}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--work",
        default=(
            "/tank/data/SFS/xinyis/data/bathymetry/MAE-Topography/"
            "Downstream_Task_Bathy"
        ),
        help="Downstream_Task_Bathy root.",
    )
    parser.add_argument("--group-name", required=True)
    parser.add_argument(
        "--member",
        action="append",
        dest="members",
        required=True,
        help="Holdout member river name. Repeat this option.",
    )
    parser.add_argument(
        "--source-fold",
        default="",
        help=(
            "Existing holdout fold used only to recover the complete train+val "
            "universe. Default: first complete fold found under cross_validation/splits."
        ),
    )
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    work = Path(args.work)
    cv_root = work / "cross_validation"
    group_name = safe_name(args.group_name)
    members = tuple(args.members)

    source_fold = args.source_fold or auto_source_fold(cv_root)
    source_split = cv_root / "splits" / f"holdout_{safe_name(source_fold)}"
    source_audit = cv_root / "audits" / f"holdout_{safe_name(source_fold)}"

    if not source_split.is_dir():
        raise FileNotFoundError(f"Missing source split: {source_split}")
    if not source_audit.is_dir():
        raise FileNotFoundError(f"Missing source audit: {source_audit}")

    pairs = load_pairs(source_split)
    records = [(river_from_dem(dem), dem, mask) for dem, mask in pairs]

    all_rivers = sorted(set(r for r, _, _ in records))
    missing_members = [m for m in members if m not in all_rivers]
    if missing_members:
        raise ValueError(
            "These group members were not found in the source fold universe: "
            f"{missing_members}\nAvailable rivers: {all_rivers}"
        )

    fieldnames, audit_index = load_audit_rows(
        [
            source_audit / "train_core_loss_audit.csv",
            source_audit / "val_core_loss_audit.csv",
        ]
    )

    split_dir = cv_root / "splits" / f"holdout_{group_name}"
    audit_dir = cv_root / "audits" / f"holdout_{group_name}"

    required_outputs = [
        split_dir / "train.txt",
        split_dir / "val.txt",
        split_dir / "train_masks.txt",
        split_dir / "val_masks.txt",
        audit_dir / "train_core_loss_audit.csv",
        audit_dir / "val_core_loss_audit.csv",
    ]
    if not args.overwrite and any(path.exists() for path in required_outputs):
        raise FileExistsError(
            f"Grouped fold already exists for {group_name}; use --overwrite."
        )

    member_set = set(members)
    train_records = [r for r in records if r[0] not in member_set]
    val_records = [r for r in records if r[0] in member_set]

    if len(train_records) + len(val_records) != len(records):
        raise RuntimeError("Internal split size mismatch.")

    write_lines(split_dir / "train.txt", (r[1] for r in train_records))
    write_lines(split_dir / "train_masks.txt", (r[2] for r in train_records))
    write_lines(split_dir / "val.txt", (r[1] for r in val_records))
    write_lines(split_dir / "val_masks.txt", (r[2] for r in val_records))
    write_lines(split_dir / "holdout_rivers.txt", members)
    write_lines(audit_dir / "holdout_rivers.txt", members)

    train_rows = [find_audit_row(audit_index, r[1]) for r in train_records]
    val_rows = [find_audit_row(audit_index, r[1]) for r in val_records]
    write_audit(audit_dir / "train_core_loss_audit.csv", fieldnames, train_rows)
    write_audit(audit_dir / "val_core_loss_audit.csv", fieldnames, val_rows)

    summary = {
        "group_name": group_name,
        "members": list(members),
        "source_fold": source_fold,
        "train_total": len(train_records),
        "val_total": len(val_records),
        "train_pass": sum((row.get("status") or "").strip() == "PASS" for row in train_rows),
        "val_pass": sum((row.get("status") or "").strip() == "PASS" for row in val_rows),
        "train_status": status_counts(train_rows),
        "val_status": status_counts(val_rows),
        "train_river_counts": dict(sorted(Counter(r[0] for r in train_records).items())),
        "val_river_counts": dict(sorted(Counter(r[0] for r in val_records).items())),
        "split_dir": str(split_dir),
        "audit_dir": str(audit_dir),
    }
    with (split_dir / "fold_summary.json").open("w") as f:
        json.dump(summary, f, indent=2)

    print("=== Grouped holdout prepared ===")
    print(f"group_name = {group_name}")
    print(f"members    = {', '.join(members)}")
    print(f"source     = {source_fold}")
    print(f"split_dir  = {split_dir}")
    print(f"audit_dir  = {audit_dir}")
    print(f"train      = {len(train_records)} total, {summary['train_pass']} PASS")
    print(f"val        = {len(val_records)} total, {summary['val_pass']} PASS")
    print("val_river_counts:")
    for river, count in summary["val_river_counts"].items():
        print(f"  {river}: {count}")
    print("val_status:", summary["val_status"])


if __name__ == "__main__":
    main()
