%% Run the staged zero-NoData patch for Santiam only.
clear; clc;

river = 'OR_SantiamRiverTB_Topobathy_1_D23';
rootPR = '/tank/data/SFS/xinyis/data/bathymetry/Processed_Results';

cd('/tank/data/SFS/xinyis/src/MEX_2.3.0');
GDALLoad();
addpath('/tank/data/SFS/xinyis/src/CREST_Prep');
% Add the folder containing these patch functions before running.

fprintf('\nSTEP 1/4: Canonicalize confirmed zero-fill bathy pixels\n');
B001_06_Canonicalize_Bathy_ZeroND_ForRiver(river, ...
    'rootPR', rootPR, ...
    'res', 1, ...
    'zeroIsNoData', true, ...
    'globalND', -999999, ...
    'overwrite', true, ...
    'doPathSetup', false);

fprintf('\nSTEP 2/4: Rebuild bathy-priority + 3DEP merge\n');
B001_07_Rebuild_Bathy3DEP_Merge_ForRiver(river, ...
    'rootPR', rootPR, ...
    'res', 1, ...
    'assertNoZero', true, ...
    'globalND', -999999, ...
    'overwrite', true, ...
    'doPathSetup', false);

fprintf('\nSTEP 3/4: Rebuild simple final prediction mask\n');
B003s_NDfix_Build_SimpleFinalMask_ForRiver(river, ...
    'rootPR', rootPR, ...
    'res', 1, ...
    'zeroIsNoDataFallback', true, ...
    'globalND', -999999, ...
    'overwrite', true, ...
    'doPathSetup', false);

fprintf('\nSTEP 4/4: Re-extract existing selected PointIDs\n');
B005b_Reextract_SelectedTiles_After_NDfix(river, ...
    'rootPR', rootPR, ...
    'res', 1, ...
    'assertNoZero', true, ...
    'globalND', -999999, ...
    'overwrite', true, ...
    'doPathSetup', false);

fprintf('\nALL STAGED SANTIAM ZERO-NODATA PATCH STEPS COMPLETED.\n');
